### ISSUE TITLE
Error when starting the application

### ISSUE THREAD

**Issue by adjoawadee** [FrontendMasters/advanced-graphql#4]
I'm able to install all dependencies. After I run the application, the GraphQL playground starts but it's accompanied with an error in the log.
`UnhandledPromiseRejectionWarning: MongoNetworkError: failed to connect to server [localhost:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 127.0.0.1:27017]
    at Pool.<anonymous> (C:\Users\ernestina.wadee\Documents\GitHub\advanced-graphql\node_modules\mongodb-core\lib\topologies\server.js:505:11)
    at emitOne (events.js:116:13)
    at Pool.emit (events.js:211:7)
    at Connection.<anonymous> (C:\Users\ernestina.wadee\Documents\GitHub\advanced-graphql\node_modules\mongodb-core\lib\connection\pool.js:329:12)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at Connection.emit (events.js:214:7)
    at Socket.<anonymous> (C:\Users\ernestina.wadee\Documents\GitHub\advanced-graphql\node_modules\mongodb-core\lib\connection\connection.js:245:50)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
(node:12940) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:12940) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
`

**Comment by antrancs** [comment]
Make sure you have started MongoDB by running "mongod" from the terminal.
