### ISSUE TITLE
Failed to start Playground 

### ISSUE THREAD

**Issue by faiz121** [FrontendMasters/advanced-graphql#7]
![image](https://user-images.githubusercontent.com/19718788/58434808-5c057780-8072-11e9-870b-6b160985a019.png)

```
Duplicate "graphql" modules cannot be used at the same time since different
versions may have different capabilities and behavior. The data from one
version used in the function from another could produce confusing and
spurious results.
    at instanceOf (/Users/faimohammed/Documents/faizrepo/advanced-graphql/node_modules/graphql/jsutils/instanceOf.js:15:13)
    at isSchema (/Users/faimohammed/Documents/faizrepo/advanced-graphql/node_modules/graphql/type/schema.js:52:35)
    at validateSchema (/Users/faimohammed/Documents/faizrepo/advanced-graphql/node_modules/graphql/type/validate.js:55:25)
    at assertValidSchema (/Users/faimohammed/Documents/faizrepo/advanced-graphql/node_modules/graphql/type/validate.js:80:16)
    at Object.validate (/Users/faimohammed/Documents/faizrepo/advanced-graphql/node_modules/graphql/validation/validate.js:58:35)
    at doRunQuery (/Users/faimohammed/Documents/faizrepo/advanced-graphql/node_modules/apollo-server-core/dist/runQuery.js:111:42)
    at /Users/faimohammed/Documents/faizrepo/advanced-graphql/node_modules/apollo-server-core/dist/runQuery.js:21:56
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
Error: Cannot use GraphQLSchema "[object GraphQLSchema]" from another module or realm.

Ensure that there is only one instance of "graphql" in the node_modules
directory. If different versions of "graphql" are the dependencies of other
relied on modules, use "resolutions" to ensure only one version is installed.

https://yarnpkg.com/en/docs/selective-version-resolutions
```

**Comment by faiz121** [comment]
@1Marc @Hendrixer

**Comment by cristian-gabbanini** [comment]
Hey!
Just made a pr to fix this issue.
This comment is just a remainder for anyone incurring into the same problem if the pr has not been merged yet.
